version: "3.3"

services:
  university-timetable:
    image: eclipse-temurin:21-alpine
    container_name: UniversityTimetable
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /opt/app
    working_dir: /opt/app
    network_mode: host
    command: ['java', '-XX:+UseShenandoahGC', '-Xmx512M', '-jar', 'UniversityTimetable-all.jar']
